"""
intelligence_system/insights/prompts/api_prompts.py

Prompt templates for the API intelligence domain.

These templates consume the structured context generated by
api_context.py and are used by api_generator.py.
"""

import json
from typing import Any


# ==========================================================
# Shared System Constraints
# ==========================================================

SYSTEM_CONSTRAINTS = """
SYSTEM CONSTRAINTS

- Use ONLY the supplied context.
- Prioritize insights that are actionable
- Avoid merely restating the data
- Never invent statistics.
- Never fabricate trends.
- Explain WHY a finding matters
- Never assume missing values.
- Distinguish between observation and interpretation.
- If evidence is insufficient, explicitly state:
  "Insufficient evidence."

- Prioritize meaningful business changes/implications over descriptive summaries.

- Every statement must reference evidence found
  inside the supplied context.

Return VALID JSON ONLY.
Do not output markdown.
Do not output explanations.

- This output will be consumed by streamlit dashboards and FASTAPI endpoints.
"""


# ==========================================================
# Product Intelligence
# ==========================================================

PRODUCT_PROMPT = """
ROLE

You are an Ecommerce Product Intelligence Analyst.

OBJECTIVE

Analyze ONLY product performance.

Ignore brands.

Ignore sellers.

CONTEXT

{context}

{constraints}

OUTPUT

{{
    "role":"product_intelligence",

    "executive_summary":"...",

    "key_findings":[
        {{
            "finding":"...",
            "evidence":"...",
            "confidence":"High|Medium|Low",
            "confidence_reason":"..."
        }}
    ],

    "opportunities":[
        {{
            "opportunity":"...",
            "rationale":"...",
            "products":[]
        }}
    ],

    "risks":[
        {{
            "risk":"...",
            "rationale":"...",
            "products":[]
        }}
    ],

    "entity_spotlights":{{
        "top_product":{{}},
        "most_improved":{{}},
        "declining_product":{{}}
    }}
}}
"""


# ==========================================================
# Brand Intelligence
# ==========================================================

BRAND_PROMPT = """
ROLE

You are an Ecommerce Brand Intelligence Analyst.

OBJECTIVE

Analyze ONLY brand performance.

Ignore products.

Ignore sellers.

CONTEXT

{context}

{constraints}

OUTPUT

{{
    "role":"brand_intelligence",

    "executive_summary":"...",

    "key_findings":[
        {{
            "finding":"...",
            "evidence":"...",
            "confidence":"High|Medium|Low",
            "confidence_reason":"..."
        }}
    ],

    "opportunities":[],

    "risks":[],

    "entity_spotlights":{{
        "top_brand":{{}},
        "fastest_rising":{{}},
        "under_pressure":{{}}
    }}
}}
"""


# ==========================================================
# Seller Intelligence
# ==========================================================

SELLER_PROMPT = """
ROLE

You are an Ecommerce Seller Intelligence Analyst.

OBJECTIVE

Analyze ONLY seller performance.

Ignore brands.

Ignore products.

CONTEXT

{context}

{constraints}

OUTPUT

{{
    "role":"seller_intelligence",

    "executive_summary":"...",

    "key_findings":[
        {{
            "finding":"...",
            "evidence":"...",
            "confidence":"High|Medium|Low",
            "confidence_reason":"..."
        }}
    ],

    "opportunities":[],

    "risks":[],

    "entity_spotlights":{{
        "top_seller":{{}},
        "most_expanding":{{}},
        "unstable":{{}}
    }}
}}
"""


# ==========================================================
# Prompt Formatter
# ==========================================================

def build_prompt(template: str, context: dict[str, Any]) -> str:
    """
    Inject serialized context into a prompt template.
    """

    serialized_context = json.dumps(
        context,
        indent=2,
        default=str
    )

    return template.format(context = serialized_context, constraints = SYSTEM_CONSTRAINTS)
     
     